spring:
  application:
    name: vanilla
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/oIDj79884W
    username: oIDj79884W
    password: OmzIpgbOkP
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: embedded
    platform: oauth2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
#    properties:
#      hibernate.format_sql: true
#  security:
#    user:
#      name: admin
#      password: admin
#      roles:
#      - read
#management:
#  context_path: /admin
#security:
#  oauth2:
#    resource:
#      filter-order: 3

#/원격지 서버 토큰 유효성 검사
#security:
#  oauth2:
#    resource:
#      token-info-uri: http://localhost/oauth/check_token
logging:
  level:
    org.springframework.security: WARN